apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-history-server
  labels:
    app: spark-history-server
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - backend:
            service:
              name: spark-history-server
              port:
                number: 80
          #/api/v1
          path: /
          pathType: Prefix
