apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore-server
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "hive-metastore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hive-metastore.labels" $ | trim | nindent 8 }}
        {{- include "hive-metastore.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["/opt/apache-hive-metastore-3.0.0-bin/bin/start-metastore"]
          #command: ["sleep"]
          #args: ["6000"]
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
         {{- end }}
          ports:
            - name: tcp
              containerPort: 9083
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9083
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 9083
          resources:
            {{- toYaml .Values.resources | trim  | nindent 12 }}
          volumeMounts:
          - name: hive-matastore-conf
            mountPath: /opt/apache-hive-metastore-3.0.0-bin/conf
      volumes:
      - name: hive-matastore-conf
        configMap:
          name: hive-matastore-conf
