apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: thrift
      protocol: TCP
      port: 9083
      targetPort: 9083
  selector:
    {{- include "hive-metastore.selectorLabels" . | nindent 4 }}
