replicaCount: 1

image:
  repository: ghcr.io/datapunchorg/spark-on-k8s-operator
  tag: spark-history-server-3.2-1650337377
  pullPolicy: IfNotPresent
  pullSecrets: []

sparkEventLogDir: file:/tmp/spark-events

resources:
  limits:
    cpu: 100m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 1024Mi
