apiVersion: v1
kind: Service
metadata:
  name: strimzi-kafka-bridge
  labels:
    app: strimzi-kafka-bridge
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: strimzi-kafka-bridge