---
## You can override the default chart name (i.e., .Charts.name) when desired using the following parameter.
## This is the only way to have more than one deployment of this
nameOverride: null

## Number of Hive Metastore instances.
## Following the documentation, given Hive Metastore is stateless we could have more than one instance.
## https://cwiki.apache.org/confluence/display/Hive/AdminManual+Metastore+Administration
replicaCount: 1

## Default Hive image and tag. Please build image locally before applying this.
image:
  name: ghcr.io/datapunchorg/helm-hive-metastore
  tag: main-1650750672

postgresServerHost: postgres-postgresql.default.svc.cluster.local
postgresServerPort: 5432
postgresUserName: postgres
postgresUserPassword: xxx
metastoreDatabaseName: metastore_db

metastoreSite:
  metastoreUris: thrift://xxx:9083
  metastoreWarehouseDir: file:///tmp/

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 1Gi

service:
  type: ClusterIP
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
      protocol: TCP

## Auto-scaling (hpa) configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90