#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Default values for kyuubi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Kyuubi server numbers
replicaCount: 1

image:
  repository: ghcr.io/datapunchorg/incubator-kyuubi
  tag: kyuubi-1652247753
  pullPolicy: IfNotPresent

probe:
  liveness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 10

server:
  bind:
    host: 0.0.0.0
    port: 10009
  conf:
    mountPath: /opt/kyuubi/conf

service:
  type: NodePort
  # The default port limit of kubernetes is 30000-32767
  # to change:
  #   vim kube-apiserver.yaml (usually under path: /etc/kubernetes/manifests/)
  #   add or change line 'service-node-port-range=1-32767' under kube-apiserver
  port: 30009
  annotations: {}

resources:
  # Used to specify resource, default unlimited.
  # If you do want to specify resources:
  #   1. remove the curly braces after 'resources:'
  #   2. uncomment the following lines
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 4Gi

serviceRegistry:
  restUrl: http://kyuubi-server-0.kyuubi-svc.spark-01.svc.cluster.local:10099/api/v1

sparkApiGateway:
  restUrl: https://a5938bf0020a0423b93aaa8d5a4784ea-1621414220.us-west-1.elb.amazonaws.com/sparkapi/v1
  user: user1
  password: password1

sparkSqlEngine:
  jarFile: s3a://datapunch-public-01/jars/kyuubi-spark-sql-engine_2.12-1.5.0-incubating.jar
