apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hive-metastore
  name: hive-metastore-server
  namespace: hive-01
spec:
  containers:
  - command:
    - /opt/apache-hive-metastore-3.0.0-bin/bin/start-metastore
    image: ghcr.io/datapunchorg/helm-hive-metastore:main-1650942144
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 20
      successThreshold: 1
      tcpSocket:
        port: 9083
      timeoutSeconds: 1
    name: hive-metastore
    ports:
    - containerPort: 9083
      name: tcp
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 9083
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/apache-hive-metastore-3.0.0-bin/conf
      name: hive-matastore-conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bgkf4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - configMap:
      defaultMode: 420
      name: hive-matastore-conf
    name: hive-matastore-conf
