apiVersion: v1
kind: Pod
metadata:
  name: hive-metastore-hook-pre-install
  annotations:
    "helm.sh/hook": "pre-install"

spec:
  containers:
    - name: hive-metastore-hook-pre-install
      image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
      imagePullPolicy: IfNotPresent
      command: [ "/opt/hive-metastore/bin/schematool -dbType postgres -initSchema" ]
      volumeMounts:
        - name: hive-conf-templates
          mountPath: /opt/hive-metastore/conf/templates

  restartPolicy: Never
  terminationGracePeriodSeconds: 0

  volumes:
    - name: hive-conf-templates
      configMap:
        name: {{ include "hive-metastore.name" . }}-conf-templates
