apiVersion: batch/v1
kind: Job
metadata:
  name: { { .Chart.Name } }-job-hook-pre-install
  annotations:
    "helm.sh/hook": "pre-install"

spec:
  template:
    spec:
      containers:
        - name: { { .Chart.Name } }-job-hook-pre-install
          image: "{{.Values.image.name}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          command: [ "/opt/hive-metastore/bin/schematool -dbType postgres -initSchema" ]

      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0

  backoffLimit: 3
  completions: 1
  Parallelism: 1