apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  labels:
    app: spark-history-server
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: spark-history-server