replicaCount: 1

image:
  name: ghcr.io/datapunchorg/strimzi-kafka-bridge:0.22.0-SNAPSHOT-1651610846
  pullPolicy: IfNotPresent
  pullSecrets: []

kafka:
  bootstrapServers: localhost:9098,another-server:9098

resources:
  limits:
    cpu: 100m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 1024Mi
