apiVersion: v1
kind: Pod
metadata:
  name: hive-metastore-init-db

spec:
  containers:
    - name: hive-metastore-init-db
      image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
      imagePullPolicy: IfNotPresent
      #command: [ 'sleep' ]
      #args: [ '6000' ]
      command: [ '/opt/hive-metastore/bin/schematool' ]
      args: [ '-initSchema', '-dbType', 'mysql', '-verbose']
      env:
      volumeMounts:
        - name: hive-matastore-init-db-conf-templates
          mountPath: /opt/apache-hive-metastore-3.0.0-bin/conf

  restartPolicy: Never
  terminationGracePeriodSeconds: 0

  volumes:
    - name: hive-matastore-init-db-conf-templates
      configMap:
        name: hive-matastore-init-db-conf-templates
